name: shared_core
description: Shared core library for ZaZa Dance Studio applications
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Backend & Database
  supabase_flutter: ^2.8.0
  
  # Utilities
  flutter_dotenv: ^5.1.0
  intl: any
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: