name: dance_studio_admin
description: ZaZa Dance Admin
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Shared Core Library
  shared_core:
    path: ../shared_core
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1
  
  # Backend & Database
  supabase_flutter: ^2.5.6
  http: ^1.1.0
  
  # Navigation & Routing
  go_router: ^13.2.1
  
  # UI & Design
  google_fonts: ^6.1.0
  flutter_staggered_grid_view: ^0.7.0
  data_table_2: ^2.5.15
  flutter_colorpicker: ^1.1.0
  
  # Images & Media
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  
  # Rich Text Editor
  html_editor_enhanced: ^2.5.1
  
  # File Management
  file_picker: ^10.3.2
  
  # Utilities
  intl: any
  uuid: ^4.5.1
  flutter_dotenv: ^5.1.0
  
  # Charts & Analytics
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # No assets needed for admin app currently

flutter_launcher_icons:
  web:
    generate: true
  image_path: "../assets/images/zaza_icon.png"